config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <h1>Our flats (<%= @flats.size %>)</h1>
  </div>
  <%# CARDS CONTAINER %>
  <div class="row mt-4">
    <% @flats.each do |flat| %>
      <%# OUTER CARDS DIV %>
      <div class="col-md-4 mb-3">
        <%# CARD CONTENT %>
        <div class="card h-100 mb-4 p-3">
          <h3><%= link_to flat.name, flat_path(flat), class: "text-decoration-none text-dark" %></h3>
          <p class="m-0"><%= flat.description %></p>
          <p><%= link_to "More info", flat_path(flat), class: "text-decoration-none fw-bold" %></p>
          <div class="row h-100 align-items-end">
            <div class="col-md-3">
              <i class="fa-solid fa-people-roof me-2"></i>
              <strong><%= flat.number_of_guests %></strong>
            </div>
            <div class="col-md-3">
              <i class="fa-solid fa-euro-sign"></i>
              <strong><%= flat.price_per_night %></strong>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-3">
  <div class="row">
    <h1>List your place...</h1>
  </div>
  <hr>
  <div class="container bg-light py-3 mb-4 rounded border">
    <%= simple_form_for [@flat] do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.submit "Add flat", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container w-50">
  <h1 class="mt-3"><%= @flat.name %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# NAV BAR %>
    <nav class="navbar bg-light">
      <div class="container-fluid">
        <%= link_to flats_path, class: "navbar-brand fw-bold" do %>
          <%= icon('fa-solid', 'bed') %>
           Simple Airbnb
        <% end %>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Find your perfect stay" aria-label="Search">
          <button class="btn btn-outline-success me-2" type="submit">Search</button>
          <%= link_to new_flat_path, class: "btn btn-success me-2" do %>
            <%= icon('fa-solid', 'building') %>
          <% end %>
          <button class="btn btn-warning" type="submit"><i class="fa-solid fa-key"></i></button>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>